version: "3.8"
services:
 
  postgres:
    image: postgres:14
    volumes:
       - ./data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  adminer:
    image: adminer:4.7
    ports:
      - "${ADMINER_PORT:-8008}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-postgresql}
      ADMINER_DEFAULT_DB_DRIVER: ${ADMINER_DEFAULT_DB_DRIVER:-pgsql}
    depends_on:
      postgres:
        condition: service_healthy
